services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=your_server_url # replace with your domain or IP
      - SERVERPORT=51820
      - PEERS=1 # number of clients
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0 # subnet for the VPN
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped